### ISSUE TITLE
404-page issue on page refresh [GSSoC'23]

### ISSUE THREAD

**Issue by Sukhendu2002** [ak736/project-marketplace#1]
whenever I refresh other than the home page it shows a 404 page, it can be solved by adding a vercel.config file, I handle this in my previous projects.  Can you assign this to me, I want to solve this 

![image](https://github.com/ak736/project-marketplace/assets/76804228/d30388ad-8657-4740-b5c3-c5a6625bc454)

**Comment by ak736** [comment]
Sure, will be working on this asap!!
