### ISSUE TITLE
CODE_OF_CONDUCT.md [GSSOC'23]

### ISSUE THREAD

**Issue by parthpathakpp1** [ak736/project-marketplace#102]
I will add CODE OF CONDUCT which will give guidelines to the contributors .

**Comment by ak736** [comment]
okay

**Comment by parthpathakpp1** [comment]
@ak736 I have raised a PR https://github.com/ak736/project-marketplace/pull/106

**Comment by parthpathakpp1** [comment]
@ak736 Can you please add label on this PR
