### ISSUE TITLE
Sidebar at bottom on small screen size

### ISSUE THREAD

**Issue by sumitkr2000** [ak736/project-marketplace#111]
Hey, @ak736 Crretnyl on the small screen size the naidebar is not displaying. I want to make it at the bottom of the page so that users can use the sidebar even at less screen size. Please assign me this issue. Thank you!

**Comment by ak736** [comment]
sure

**Comment by sumitkr2000** [comment]
Hey @ak736 I have attached the screenshot. Please check if it looks good.

- Large device:

![image](https://github.com/ak736/project-marketplace/assets/100675296/e0a463c4-4f5f-4738-90da-763d6e37a5c4)

- Medium device:

![image](https://github.com/ak736/project-marketplace/assets/100675296/39d60fa7-3a5c-4941-af21-d43385bddc7e)

- Small device:

![image](https://github.com/ak736/project-marketplace/assets/100675296/a68ab59e-42b5-4709-8182-5cf0a3d4bee3)

**Comment by sumitkr2000** [comment]
@ak736 Please review this.
