### ISSUE TITLE
Add Payload Validation

### ISSUE THREAD

**Issue by madhur87** [ak736/project-marketplace#12]
Add Joi Validation to validate the API payload in Backend.
Please Assign me! @ak736

**Comment by ak736** [comment]
Sure

**Comment by madhur87** [comment]
Can you reopen the issue, I think by mistake you have close the issue @ak736

**Comment by madhur87** [comment]
It give an error when I was trying to push a code, is there any permission required to push the code? 

remote: Permission to ak736/project-marketplace.git denied to madhur87

@ak736
