### ISSUE TITLE
Add Bcrypt Password

### ISSUE THREAD

**Issue by madhur87** [ak736/project-marketplace#15]
Add Bcrypt Password Functionality and Decode on Authentication Time

https://www.npmjs.com/package/bcrypt

Please assign me! @ak736

**Comment by madhur87** [comment]
In the application, bcrypt method is already present but it is not working, in db they are storing without bcrypt format

**Comment by Dharansh-Neema** [comment]
I can also work on the same

**Comment by ak736** [comment]
Assigned you

**Comment by madhur87** [comment]
[MR](https://github.com/ak736/project-marketplace/pull/29)
