### ISSUE TITLE
LOGIN/SIGNUP-feature

### ISSUE THREAD

**Issue by 007xylogramori** [ak736/project-marketplace#2]
I would like to add the login and signup feature as part of **### _Gssoc'23_**

I would use JWT and Bcrypt to make a smooth and secure login/signup feature.

**Comment by abhipatel0211** [comment]
hello is someone working on this feature i want to work on this feature can you assign me this project?

**Comment by aniketburman014** [comment]
Hello I want to work on this project.

**Comment by ninjahattori21** [comment]
Hello, I would like to take on the project of creating a login/signup feature for a website that involves financial transactions. I plan to implement  **JWT** authentication at the backend, which will not only work for the login and transaction processes but also integrate with the add-to-cart functionality. I am confident in my ability to address any issues that may arise. Please assign me this project as I am eager to contribute and resolve any issues that may arise.

**### Gssoc'23**

**Comment by ak736** [comment]
Okay sure

**Comment by abhipatel0211** [comment]
Okay sure
