### ISSUE TITLE
Add hover effect to the buttons!

### ISSUE THREAD

**Issue by tanayvaswani** [ak736/project-marketplace#20]
While hovering over the buttons on the website, we cannot actually see any changes. It looks odd because hovering is one of the basic features of the button. 
![Screenshot (26)](https://github.com/ak736/project-marketplace/assets/114291962/34c3d348-aabb-49bc-a408-bff8e7a71a93)

**Comment by tanayvaswani** [comment]
@ak736 Please add the GSSoC label to this issue and assign this to me. Thanks.

**Comment by ak736** [comment]
Sure
