### ISSUE TITLE
Sign up component

### ISSUE THREAD

**Issue by vikram-8290** [ak736/project-marketplace#23]
Hiii @ak736 
i want to create a sign up component 
**Please assign mw this task**

**Comment by mvpfrever** [comment]
hello sir @ak736  it will be my pleasure if i create singup component please assign this task to me

**Comment by vikram-8290** [comment]
> hello sir @ak736 it will be my pleasure if i create singup component please assign this task to me

please search a unique issue and stop commenting on other peoples issues or ideas, i think you need to step out of computer science

**Comment by ak736** [comment]
Sure do it.

**Comment by mvpfrever** [comment]
> Sure do it.

sir is it completed ?

**Comment by ak736** [comment]
No, if you want to do. Go ahead, I already assigned you.

**Comment by vikram-8290** [comment]
Hii @ ak736,
I have designed the Sign up component But not sure to link this so it work properly.
Is there any platform where i ask query regarding this? Please let me Know

**Comment by ak736** [comment]
Ping me on twitter @aniket736

**Comment by mvpfrever** [comment]
@ak736  since last 2 days i tring to run it but it is showing error that can find script file

**Comment by vikram-8290** [comment]
Hiii @ak736 ,
sorry i was not able contact you due my college internals exam , i will reaching you out as soon as possible.
once again sorry for delay.

**Comment by vikram-8290** [comment]
Hii @ak736 Sir , 
i am ready with my Code,
it will be helpful if i can understand the codebase so i know where to link this Sign up Component,
Sorry for the Trouble
