### ISSUE TITLE
Integrating Blockchain, enabling the adding and view of projects

### ISSUE THREAD

**Issue by Kaushan-Dutta** [ak736/project-marketplace#24]
## Problem
Currently the app is just integrating the blockchain only while connecting the wallet. And also there is no way the user can upload the course in the application and sell it.
## Resolve
To create a project market place, I will be adding the smart contract where the user can add their own project, and also integrating the sell and the purchase of the course.

**Comment by ak736** [comment]
Assigned you!!

**Comment by Kaushan-Dutta** [comment]
> Assigned you!!

can you just add the gssoc 23 tag for this issue
