### ISSUE TITLE
navbar is not available in mobile view

### ISSUE THREAD

**Issue by Iamdivyak** [ak736/project-marketplace#25]
There is no navbar in the mobile view

<img width="221" alt="image" src="https://github.com/ak736/project-marketplace/assets/102896170/e4738880-c2c2-4be7-8668-f180b1febf37">

I can add a navbar. 
All these👇🏻 links, I can add in Navbar in the mobile view
<img width="176" alt="image" src="https://github.com/ak736/project-marketplace/assets/102896170/32b88a6a-00ab-42cd-8a1c-a1e5e4dc8bc1">

Kindly assign this task to me under gssoc contributor

**Comment by ak736** [comment]
You can try now.
