### ISSUE TITLE
add readme badges

### ISSUE THREAD

**Issue by S-ishita** [ak736/project-marketplace#34]
I want to add readme badges.Please assign this issue to me 
![badges](https://github.com/ak736/project-marketplace/assets/104543751/a85d29b2-fdec-41ff-9ca2-b2c2720c3b85)

**Comment by ak736** [comment]
Sure

**Comment by S-ishita** [comment]
Hey why did you close this? @ak736

**Comment by ak736** [comment]
I assigned you, you can start working on it. For more query dm me on twitter @aniket736
