### ISSUE TITLE
Creating  a Login Page

### ISSUE THREAD

**Issue by Hemant2335** [ak736/project-marketplace#39]
As there is button for login page but it don't really works .

-> I can make you a working login page for you but in this I will be working on frontend
-> And will create a quite good login page

Therefore please assign this task to me under GSSOC'23

Thank you

**Comment by ak736** [comment]
Yes we need it

**Comment by Hemant2335** [comment]
Ok Thank you ,  but why you closed it as completed

**Comment by ak736** [comment]
I'm having so much of the issues raised, it's difficult to keep open each and every issue.

**Comment by Hemant2335** [comment]
So I have to work on it right !! Thank you
