### ISSUE TITLE
Responsive navbar [GSSOC23]

### ISSUE THREAD

**Issue by Km7654** [ak736/project-marketplace#43]
Hi!
I am Kaushik Singh. I would like to contribute to this project by enhancing the navbar and making it responsive, as we reduce the width the navbar disappear and there is no way to navigate to different pages.

**Comment by ak736** [comment]
Sure

**Comment by ak736** [comment]
Can you fix the nav bar and all tbe components acc to the screen.

**Comment by ak736** [comment]
I'm closing this issue since no any updates from your side.
