### ISSUE TITLE
Improve the UI of the project

### ISSUE THREAD

**Issue by sumitkr2000** [ak736/project-marketplace#5]
Hey @ak736 I can see that the Ui of your website is not up to the mark. I can help improve the UI of your website. Please assign me this issue so that I can starting working on it. Thank you!

**Comment by SONA-1111** [comment]
Hi! I would like to contribute to this issue under the GSSoC'23. It seems interesting and aligned with my skills. I would be happy to take it up and work on this project.

**Comment by SONA-1111** [comment]
Hi! I would like to contribute to this issue under the GSSoC'23. It seems interesting and aligned with my skills. I would be happy to take it up and work on this project.

**Comment by sumitkr2000** [comment]
@SONA-1111 please raise another issue. I have already raised this issue and will be working on it. Thank you!

**Comment by ak736** [comment]
Try working on it.

**Comment by sumitkr2000** [comment]
Bro why did u closed this issue??? @ak736

**Comment by sumitkr2000** [comment]
@ak736 Should I work on it or not?
