### ISSUE TITLE
 Subject: 404 Error Occurs on Refreshing Deployed Website Route  Example : /dashboard

### ISSUE THREAD

**Issue by Nishitbaria** [ak736/project-marketplace#51]
I wanted to report an issue related to the deployed website of the project marketplace. When I navigate to the dashboard page and try to refresh the page (specifically at the URL: https://the-project-marketplace.vercel.app/dashboard), a 404 error occurs. It seems that the page is not found or unavailable.

Steps to reproduce the issue:
1. Open the URL: https://the-project-marketplace.vercel.app/dashboard
2. Wait for the page to load completely.
3. Refresh the page using the browser's refresh button or by pressing F5.

Expected behavior:
The page should refresh successfully and display the dashboard content.

Actual behavior:
Upon refreshing the page, a 404 error is encountered.

 I have fixed it  you can assign me And you can merge my PR.

you can try at https://project-marketplace-five.vercel.app/dashboard

**Comment by ak736** [comment]
Sure

**Comment by ak736** [comment]
Give a PRA

**Comment by Nishitbaria** [comment]
I Have Already Raised PR For This:  https://github.com/ak736/project-marketplace/pull/52#issue-1722645127

**Comment by Nishitbaria** [comment]
Fixing 404 Error on Refreshing Website Route so i am closing the Issue now.
