### ISSUE TITLE
No option to disconnect Wallet | GSSoC 2k23

### ISSUE THREAD

**Issue by Manice18** [ak736/project-marketplace#55]
![image](https://github.com/ak736/project-marketplace/assets/91601706/bb2a5cc7-0844-4622-bc67-a97b5541a4c1)

afteer the wallet is connected, there is no way to disconnect it

**Comment by Manice18** [comment]
I could work on this issue.

**Comment by ak736** [comment]
You can disconnect through your metamask as well, but your idea also works.
