### ISSUE TITLE
Adding animations to buttons

### ISSUE THREAD

**Issue by Indira-kumar** [ak736/project-marketplace#8]
Description:
Currently, the buttons on our website lack interactivity, leading to a static user experience.

Screenshots:
![image](https://github.com/ak736/project-marketplace/assets/74497486/1f736238-15aa-4eec-bcaf-dda1a063401e)
![image](https://github.com/ak736/project-marketplace/assets/74497486/83b8a2cf-9605-4625-acff-98a2a7b7cdc7)

Expected Outcome:
By adding animations to buttons, we can enhance the interactivity on our website, resulting in a more engaging and interactive user experience.

@ak736 Please assign me this issue under GSSOC'23, I would love to work on this

**Comment by ak736** [comment]
Try it.
