### ISSUE TITLE
Adding Hover effects for the project list

### ISSUE THREAD

**Issue by Indira-kumar** [ak736/project-marketplace#9]
Description:
The UI lacks interactivity without hover effects on the cards, also the user can go to the specific project by clicking on the card component as well, than by just clicking "view more" button. That will be more user friendly if both the button and the entire cart directs to project details page.

ScreenShots:
![image](https://github.com/ak736/project-marketplace/assets/74497486/3d16710a-e1d6-4cfc-acee-3794fe145dde)

@ak736 I would like to work on this issue under GSSOC'23.

**Comment by ak736** [comment]
Sure
