### ISSUE TITLE
Feat : Slicing of Address on navbar

### ISSUE THREAD

**Issue by shobhitexe** [ak736/project-marketplace#98]
Hey i see on Navbar full wallet address is being visible 
like we see on below SS
![image](https://github.com/ak736/project-marketplace/assets/29349136/4b606857-9058-4554-84cd-e88f9bf4fe54)

i feel it will look more good if we slice it like we see on below SS
![image](https://github.com/ak736/project-marketplace/assets/29349136/2eb5f260-c992-4db2-ad49-149addb2e69b)

Lemme know what you think if yes i would love to create a PR on this Thanks

**Comment by ak736** [comment]
Sure do it
